export class Subscriber {
    id: string = "";
    userId: string = "";
    clientType: string = "";
    companyName: string = "";
    trainerAssigned: string = "";
    country: string = "";
    FreeprofessionaltypeAcronym: string = "";
    civilliabilityinsurancefileid: string = "";
    civilliabilityinsurancefilename: string = "";
    curriculumvitaefileid: string = "";
    curriculumvitaefilename: string = "";
    freeprofessionaltypeid: string = "";
    identificationfileid: string = "";
    identificationfilename: string = "";
    name: string = "";
    paytpv: string = "";
    servicerates: string = "";
    userid: string = "";
}
