export class Subscriber {
    id: string = "";
    scid: string = "";
    userId: string = "";
    firstsurname: string = "";
    middlesurname: string = "";
    clientType: string = "";
    companyName: string = "";
    trainerAssigned: string = "";
    email: string = "";
    country: string = "";
    FreeprofessionaltypeAcronym: string = "";
    civilliabilityinsurancefileid: string = "";
    civilliabilityinsurancefilename: string = "";
    curriculumvitaefileid: string = "";
    curriculumvitaefilename: string = "";
    freeprofessionaltypeid: string = "";
    identificationfileid: string = "";
    identificationfilename: string = "";
    name: string = "";
    paytpv: string = "";
    servicerates: string = "";
    userid: string = "";
    clienttype: string = "";
    city?: string;
    address?: string;
    zipCode?: string;
    landline?: string;
    mobilePhone?: string;
    web?: string;
    referrer?: string;
}
