export class PerformanceFreeProfessional {
  id: string = "";
  proyectManagerId: string = "";
  summary: string = "";
  date: string = "";
  type: string = "";
  justifyingDocument: string = "";
  freeProfessionalWorkHours: string = "";
  freeProfessionalTravelHours: string = "";
  freeProfessionalTravelExpenses: string = "";
  freeProfessionalRemuneration: string = "";
  technicalDirectorDate: string = "";
  technicalDirectorWorkHours: string = "";
  technicalDirectorTravelHours: string = "";
  technicalDirectorTravelExpenses: string = "";
  technicalDirectorRemuneration: string = "";
  freeprofessionalId: string = "";
  estimatedWorkHours: string = "";
  estimatedTransportHours: string = "";
  estimatedTransportExpenses: string = "";
  justifyChangeEstimatedWorkHours: string = "";
}
